import type { GuideArticle } from "./types";
import { editorialVisuals } from "./visuals";

const editorialLabel = { tr: "Editoryal rehber", en: "Editorial guide" } as const;

export const guideArticles = [
  {
    slug: "el-yapimi-urun-kontrol-listesi",
    status: "editorial",
    title: { tr: "El yapımı ürün satın alırken kontrol listesi", en: "A checklist for buying handmade products" },
    summary: { tr: "Malzeme, ölçü, bakım ve üretim süresini karşılaştırırken kullanabileceğiniz sade bir çerçeve.", en: "A practical framework for comparing materials, dimensions, care, and production time." },
    cover: { src: editorialVisuals.productPhoto, alt: { tr: "Doğal ışıkta düzenlenmiş el yapımı ürünler", en: "Handmade products arranged in natural light" } },
    readingMinutes: 5,
    category: { tr: "Bilinçli seçim", en: "Thoughtful buying" },
    editorialLabel,
    intro: { tr: "El yapımı bir ürünü değerlendirirken kusursuz eşleşme yerine açık bilgi ve beklenti uyumu aramak daha sağlıklı bir başlangıçtır.", en: "When evaluating a handmade item, clear information and aligned expectations matter more than factory-like uniformity." },
    sections: [
      {
        id: "before-buying",
        title: { tr: "Ürün sayfasında önce bunlara bakın", en: "Start with these product-page details" },
        paragraphs: { tr: ["Açıklamanın ürünün malzemesini, yaklaşık ölçüsünü ve hazırlık biçimini netleştirmesi gerekir."], en: ["The description should clarify the material, approximate dimensions, and how the item is prepared."] },
        bullets: { tr: ["Malzeme ve yüzey bilgisi", "Ölçü veya porsiyon", "Hazırlık süresi", "Bakım ve saklama notu"], en: ["Material and finish", "Dimensions or portion", "Preparation time", "Care or storage note"] },
      },
      {
        id: "ask-maker",
        title: { tr: "Belirsiz noktaları üreticiye sorun", en: "Ask the maker about unclear details" },
        paragraphs: { tr: ["Renk, ölçü veya teslim alma koşulu kararınızı etkiliyorsa sipariş talebinden önce kısa ve somut bir soru yöneltin."], en: ["If color, size, or handover terms affect your decision, ask a short and specific question before requesting an order."] },
      },
    ],
    conclusion: { tr: "İyi bir seçim; ürünün fotoğrafı, açıklaması ve üreticinin verdiği bilgiler birbiriyle tutarlı olduğunda başlar.", en: "A sound choice begins when the photos, description, and maker-provided details are consistent." },
    relatedSlugs: ["malzeme-bilgisi-okuma", "siparis-uzerine-uretim"],
  },
  {
    slug: "yerel-ureticiyi-desteklemek",
    status: "editorial",
    title: { tr: "Yerel üreticiyi desteklemek ne anlama gelir?", en: "What does supporting a local maker mean?" },
    summary: { tr: "Yerel alışverişin ölçek, iletişim ve üretim görünürlüğü açısından sunduğu olanaklar.", en: "How local shopping can improve visibility into scale, communication, and production." },
    cover: { src: editorialVisuals.localMarket, alt: { tr: "Yerel pazarda ürünlerini düzenleyen üreticiler", en: "Makers arranging goods at a local market" } },
    readingMinutes: 4,
    category: { tr: "Yerel üretim", en: "Local making" },
    editorialLabel,
    intro: { tr: "Yerel üreticiyi desteklemek yalnızca yakın bir noktadan alışveriş yapmak değildir; ürünün arkasındaki emeği ve küçük ölçekli üretim koşullarını görünür kılmaktır.", en: "Supporting a local maker is more than shopping nearby; it makes the labor and small-scale conditions behind an item more visible." },
    sections: [
      { id: "visibility", title: { tr: "Üretim hakkında daha açık iletişim", en: "Clearer communication about production" }, paragraphs: { tr: ["Malzeme, hazırlık süresi ve teslim biçimi hakkında doğrudan soru sorabilmek beklentileri daha erken netleştirir."], en: ["Being able to ask directly about materials, lead time, and delivery can clarify expectations earlier."] } },
      { id: "choice", title: { tr: "Bilinçli destek nasıl olur?", en: "What thoughtful support looks like" }, paragraphs: { tr: ["İhtiyacınıza uyan ürünü seçin, açıklamayı okuyun ve üreticinin belirttiği hazırlık süresine alan tanıyın."], en: ["Choose an item that fits your needs, read the description, and allow for the lead time stated by the maker."] }, bullets: { tr: ["Yaklaşık bölgeyi değerlendirin", "Küçük üretim süresini hesaba katın", "Net ve saygılı iletişim kurun"], en: ["Consider the approximate area", "Account for small-batch lead time", "Communicate clearly and respectfully"] } },
    ],
    conclusion: { tr: "Yerel seçim, ürünün gerçekten ihtiyacınıza uyduğu ve koşulların şeffaf olduğu durumda anlam kazanır.", en: "A local choice is most meaningful when the item genuinely fits your needs and its terms are transparent." },
    relatedSlugs: ["yakindaki-ureticilerden-alisveris", "kucuk-uretim-seri-uretim"],
  },
  {
    slug: "ev-yapimi-gida-sorulari",
    status: "editorial",
    title: { tr: "Ev yapımı gıdalarda üreticiye sorulacak sorular", en: "Questions to ask about homemade food" },
    summary: { tr: "İçerik, alerjen, saklama ve teslim zamanı hakkında karar vermeyi kolaylaştıran sorular.", en: "Questions about ingredients, allergens, storage, and handover timing." },
    cover: { src: editorialVisuals.preserves, alt: { tr: "Ev yapımı gıda hazırlığı için düzenlenmiş mutfak yüzeyi", en: "A kitchen surface arranged for homemade food preparation" } },
    readingMinutes: 5,
    category: { tr: "Mutfak", en: "Kitchen" },
    editorialLabel,
    intro: { tr: "Gıda tercihinde ürün açıklaması ilk kaynaktır; eksik kalan kritik bilgiler doğrudan üreticiye sorulmalıdır.", en: "The product description is the first source for food choices; critical missing details should be asked directly of the maker." },
    sections: [
      { id: "ingredients", title: { tr: "İçerik ve alerjen bilgisi", en: "Ingredients and allergen information" }, paragraphs: { tr: ["Bir alerjiniz veya özel tüketim ihtiyacınız varsa yalnız ürün adına güvenmeyin. İçerik listesini ve çapraz temas ihtimalini sorun."], en: ["If you have an allergy or specific dietary need, do not rely on the product name alone. Ask about the ingredient list and possible cross-contact."] }, bullets: { tr: ["Tam içerik listesi nedir?", "Bilinen alerjenler hangileri?", "Aynı ortamda başka alerjenler işleniyor mu?"], en: ["What is the full ingredient list?", "Which known allergens are present?", "Are other allergens handled in the same space?"] } },
      { id: "storage", title: { tr: "Saklama ve teslim", en: "Storage and handover" }, paragraphs: { tr: ["Teslimden sonra ürünün nasıl ve ne kadar süre saklanması gerektiğini öğrenin. Bu bilgiler sağlık garantisi değil, doğru kullanım için üreticinin açıklamasıdır."], en: ["Ask how and for how long the item should be stored after handover. This is maker guidance for proper use, not a health guarantee."] } },
    ],
    conclusion: { tr: "Şüphe duyduğunuz bir içerik veya saklama koşulu varsa ürünü satın almadan önce profesyonel sağlık görüşü alın.", en: "If an ingredient or storage condition concerns you, seek qualified health guidance before purchasing." },
    relatedSlugs: ["guvenli-teslim-alma", "el-yapimi-urun-kontrol-listesi"],
    note: { tr: "Bu içerik tıbbi veya beslenme tavsiyesi değildir.", en: "This content is not medical or nutritional advice." },
  },
  {
    slug: "seramik-urun-bakimi",
    status: "editorial",
    title: { tr: "Seramik ürünlerin bakımı nasıl yapılır?", en: "How to care for ceramic pieces" },
    summary: { tr: "Elde şekillendirilmiş seramikleri temizlerken ve saklarken izlenebilecek temel adımlar.", en: "Basic steps for cleaning and storing hand-shaped ceramics." },
    cover: { src: editorialVisuals.ceramics, alt: { tr: "Atölyede sırlı el yapımı seramik parçalar", en: "Glazed handmade ceramic pieces in a studio" } },
    readingMinutes: 4,
    category: { tr: "Bakım", en: "Care" },
    editorialLabel,
    intro: { tr: "Seramik bakımında en güvenilir kaynak, ürünün sır ve pişirim özelliklerini bilen üreticidir.", en: "The maker who knows the glaze and firing method is the most reliable source for ceramic care." },
    sections: [
      { id: "cleaning", title: { tr: "Nazik temizlik", en: "Gentle cleaning" }, paragraphs: { tr: ["Üretici aksi yönde bilgi vermediyse ılık su, yumuşak bir sünger ve aşındırıcı olmayan temizleyici tercih edin."], en: ["Unless the maker says otherwise, use lukewarm water, a soft sponge, and a non-abrasive cleaner."] } },
      { id: "thermal", title: { tr: "Ani ısı değişimlerinden kaçının", en: "Avoid sudden temperature changes" }, paragraphs: { tr: ["Buzdolabından çıkan bir parçayı doğrudan sıcak yüzeye koymak gibi ani geçişler çatlama riskini artırabilir."], en: ["Sudden transitions, such as moving a piece from the refrigerator to a hot surface, may increase the risk of cracking."] }, bullets: { tr: ["Bulaşık makinesi uygunluğunu sorun", "Mikrodalga ve fırın kullanımını doğrulayın", "Parçaları birbirine çarpmadan saklayın"], en: ["Ask whether it is dishwasher safe", "Confirm microwave and oven suitability", "Store pieces so they do not knock together"] } },
    ],
    conclusion: { tr: "Her seramik aynı değildir; ürün özelindeki bakım notu genel öneriden önce gelir.", en: "Not all ceramics are alike; item-specific care instructions take priority over general advice." },
    relatedSlugs: ["malzeme-bilgisi-okuma", "el-yapimi-urun-kontrol-listesi"],
  },
  {
    slug: "ahsap-mutfak-urunleri-bakimi",
    status: "editorial",
    title: { tr: "Ahşap mutfak ürünleri nasıl korunur?", en: "How to protect wooden kitchenware" },
    summary: { tr: "Ahşap sunum ve mutfak ürünlerinde temizlik, kurutma ve yüzey bakımının temelleri.", en: "Cleaning, drying, and surface-care basics for wooden serving and kitchen pieces." },
    cover: { src: editorialVisuals.wood, alt: { tr: "Doğal ahşap mutfak gereçleri", en: "Natural wooden kitchen utensils" } },
    readingMinutes: 4,
    category: { tr: "Bakım", en: "Care" },
    editorialLabel,
    intro: { tr: "Ahşabın türü ve yüzey işlemi bakım biçimini değiştirir; önce üreticinin notunu kontrol edin.", en: "Wood species and surface treatment affect care, so check the maker's instructions first." },
    sections: [
      { id: "washing", title: { tr: "Yıkama ve kurutma", en: "Washing and drying" }, paragraphs: { tr: ["Uzun süre suda bırakmamak, yıkama sonrası yüzeyi silmek ve hava alarak kurumasını sağlamak genel olarak güvenli bir yaklaşımdır."], en: ["Avoiding long soaking, wiping after washing, and allowing airflow while drying is generally a safe approach."] } },
      { id: "surface", title: { tr: "Yüzey yenileme", en: "Refreshing the surface" }, paragraphs: { tr: ["Ürüne uygulanmış yağ veya kaplamayı bilmeden bakım ürünü kullanmayın. Gıda temasına uygunluk konusunda üreticiye sorun."], en: ["Do not apply a care product without knowing the existing oil or finish. Ask the maker about food-contact suitability."] }, bullets: { tr: ["Bulaşık makinesinden kaçının", "Nemli bırakmayın", "Koku veya çatlak oluşursa kullanımı değerlendirin"], en: ["Avoid the dishwasher", "Do not leave it damp", "Reassess use if odors or cracks develop"] } },
    ],
    conclusion: { tr: "Düzenli ve doğru kurutma, ahşap ürün bakımının en önemli parçalarından biridir.", en: "Consistent and proper drying is one of the most important parts of wooden-item care." },
    relatedSlugs: ["malzeme-bilgisi-okuma", "guvenli-teslim-alma"],
  },
  {
    slug: "el-orgusu-urun-bakimi",
    status: "editorial",
    title: { tr: "El örgüsü ürünlerin bakımı", en: "Caring for hand-knitted and crocheted items" },
    summary: { tr: "Lif türünü, yıkama yöntemini ve formu korumayı birlikte düşünmek için kısa rehber.", en: "A short guide to fiber type, washing method, and preserving shape." },
    cover: { src: editorialVisuals.textile, alt: { tr: "Yakından görülen el örgüsü tekstil dokusu", en: "Close view of a hand-crocheted textile texture" } },
    readingMinutes: 4,
    category: { tr: "Tekstil", en: "Textiles" },
    editorialLabel,
    intro: { tr: "Pamuk, yün ve sentetik karışımlar aynı bakım koşullarına sahip değildir. Ürün etiketini veya üretici notunu saklayın.", en: "Cotton, wool, and synthetic blends do not share the same care requirements. Keep the product label or maker note." },
    sections: [
      { id: "wash", title: { tr: "Yıkamadan önce", en: "Before washing" }, paragraphs: { tr: ["Renk verme, çekme ve aksesuarların zarar görme ihtimalini azaltmak için sıcaklık ve program bilgisini doğrulayın."], en: ["Confirm temperature and cycle guidance to reduce the risk of color transfer, shrinking, or accessory damage."] } },
      { id: "shape", title: { tr: "Formunu koruma", en: "Preserving the shape" }, paragraphs: { tr: ["Ağır örgüleri asarak kurutmak esnemeye neden olabilir. Üretici uygunsa düz zeminde, doğal formuna getirerek kurutmayı önerebilir."], en: ["Hanging heavy knitwear can cause stretching. When suitable, the maker may recommend reshaping and drying flat."] }, bullets: { tr: ["Aksesuarları kontrol edin", "Düşük sürtünme tercih edin", "Tam kurumadan kaldırmayın"], en: ["Check attached hardware", "Prefer low friction", "Do not store before fully dry"] } },
    ],
    conclusion: { tr: "Bakım talimatı görünmüyorsa satın almadan önce lif içeriğini ve yıkama önerisini sorun.", en: "If care guidance is missing, ask about fiber content and washing recommendations before buying." },
    relatedSlugs: ["malzeme-bilgisi-okuma", "siparis-uzerine-uretim"],
  },
  {
    slug: "siparis-uzerine-uretim",
    status: "editorial",
    title: { tr: "Sipariş üzerine üretim ne demektir?", en: "What does made to order mean?" },
    summary: { tr: "Hazırlık süresi, kişiselleştirme ve doğal farklılıklar konusunda gerçekçi beklenti kurma rehberi.", en: "A guide to realistic expectations around lead time, customization, and natural variation." },
    cover: { src: editorialVisuals.workshop, alt: { tr: "Küçük bir atölyede elde şekillendirilen ürün", en: "An item being shaped by hand in a small studio" } },
    readingMinutes: 5,
    category: { tr: "Üretim süreci", en: "Making process" },
    editorialLabel,
    intro: { tr: "Sipariş üzerine üretimde ürün, talep sonrasında hazırlanır. Bu ifade otomatik olarak kişiselleştirme veya kesin teslim tarihi anlamına gelmez.", en: "Made to order means the item is prepared after a request. It does not automatically imply customization or a guaranteed delivery date." },
    sections: [
      { id: "lead-time", title: { tr: "Hazırlık süresini netleştirin", en: "Clarify the lead time" }, paragraphs: { tr: ["Ürün sayfasındaki süre tahmini başlangıç noktasıdır. Malzeme tedariği veya üretim sırası bu süreyi etkileyebilir."], en: ["The estimate on the product page is a starting point. Material availability and the maker's queue may affect it."] } },
      { id: "variation", title: { tr: "El yapımındaki doğal farklılıklar", en: "Natural handmade variation" }, paragraphs: { tr: ["Doku, desen veya ton küçük ölçüde değişebilir. Kararınız için kritik bir özellik varsa bunu önceden belirtin."], en: ["Texture, pattern, or tone may vary slightly. If a feature is critical to your decision, state it in advance."] }, bullets: { tr: ["Hazırlık süresini sorun", "Değiştirilebilir alanları doğrulayın", "Teslim koşulunu netleştirin"], en: ["Ask about lead time", "Confirm customizable details", "Clarify handover terms"] } },
    ],
    conclusion: { tr: "Açık kapsam ve gerçekçi süre beklentisi, sipariş üzerine üretimde iki taraf için de daha sağlıklı bir deneyim oluşturur.", en: "A clear scope and realistic timing create a better made-to-order experience for both sides." },
    relatedSlugs: ["kucuk-uretim-seri-uretim", "el-yapimi-urun-kontrol-listesi"],
  },
  {
    slug: "malzeme-bilgisi-okuma",
    status: "editorial",
    title: { tr: "Ürün açıklamalarındaki malzeme bilgisi nasıl okunur?", en: "How to read material information in product descriptions" },
    summary: { tr: "Ana malzeme, kaplama, karışım ve bakım ilişkisini anlamaya yardımcı bir sözlük.", en: "A practical glossary for base materials, coatings, blends, and care." },
    cover: { src: editorialVisuals.materials, alt: { tr: "Farklı doğal malzeme ve dokulardan oluşan örnekler", en: "Samples showing different natural materials and textures" } },
    readingMinutes: 5,
    category: { tr: "Ürün bilgisi", en: "Product information" },
    editorialLabel,
    intro: { tr: "Malzeme adı tek başına ürünün dayanıklılığını veya kullanım alanını garanti etmez; yapım tekniği ve yüzey işlemi de önemlidir.", en: "A material name alone does not guarantee durability or suitability; construction and surface treatment matter too." },
    sections: [
      { id: "terms", title: { tr: "Ana malzeme ve yüzey işlemi", en: "Base material and surface treatment" }, paragraphs: { tr: ["“Kaplama”, “sır”, “astar” veya “karışım” gibi ifadeler ürünün ana gövdesinden farklı bir katmanı ya da bileşimi anlatabilir."], en: ["Terms such as “plated,” “glazed,” “lined,” or “blend” may describe a layer or composition different from the main body."] } },
      { id: "questions", title: { tr: "Eksik bilgide sorulabilecekler", en: "Questions when details are missing" }, paragraphs: { tr: ["Cilt teması, gıda teması veya sık yıkama gibi kullanım biçimleri için ürün özelinde bilgi isteyin."], en: ["Ask for item-specific information when it will touch skin or food, or be washed frequently."] }, bullets: { tr: ["Ana malzeme nedir?", "Yüzey işlemi veya kaplama var mı?", "Hangi bakım yöntemi öneriliyor?"], en: ["What is the base material?", "Is there a finish or coating?", "Which care method is recommended?"] } },
    ],
    conclusion: { tr: "Malzeme bilgisini kullanım amacıyla birlikte okumak, daha doğru karşılaştırma yapmanızı sağlar.", en: "Reading material information alongside intended use enables a more useful comparison." },
    relatedSlugs: ["seramik-urun-bakimi", "ahsap-mutfak-urunleri-bakimi"],
  },
  {
    slug: "yakindaki-ureticilerden-alisveris",
    status: "editorial",
    title: { tr: "Yakındaki üreticilerden alışveriş yaparken", en: "Shopping from makers in your area" },
    summary: { tr: "Yaklaşık konum, teslim alma ve kişisel adres gizliliği için dikkat edilecek noktalar.", en: "What to consider about approximate location, handover, and address privacy." },
    cover: { src: editorialVisuals.community, alt: { tr: "Birlikte üretim yapan kişilerin elleri ve çalışma yüzeyi", en: "Makers' hands around a shared work surface" } },
    readingMinutes: 4,
    category: { tr: "Yakınında", en: "Nearby" },
    editorialLabel,
    intro: { tr: "Yakındaki keşif, kesin ev adreslerinin paylaşılması anlamına gelmez. İl ve ilçe gibi yaklaşık alan bilgisi çoğu karşılaştırma için yeterlidir.", en: "Nearby discovery does not require sharing exact home addresses. Approximate city and district information is enough for most comparisons." },
    sections: [
      { id: "privacy", title: { tr: "Yaklaşık alanı kullanın", en: "Use an approximate area" }, paragraphs: { tr: ["Üretici ve alıcı, teslimat kararı kesinleşmeden kişisel adres paylaşmamalıdır. Kamusal ve uygun teslim noktaları değerlendirilebilir."], en: ["Makers and buyers should avoid sharing personal addresses before handover details are confirmed. Suitable public meeting points may be considered."] } },
      { id: "handover", title: { tr: "Teslim öncesi netleştirin", en: "Clarify before handover" }, paragraphs: { tr: ["Saat aralığı, teslim şekli ve varsa ücret bilgisini yazılı olarak karşılaştırın."], en: ["Compare the time window, handover method, and any fee in writing."] }, bullets: { tr: ["Kesin adres istemeyin", "Yaklaşık bölgeyi teyit edin", "Plan değişirse haber verin"], en: ["Do not request an exact home address", "Confirm the approximate area", "Communicate schedule changes"] } },
    ],
    conclusion: { tr: "Konum bilgisi yalnız gerekli olduğu ölçüde paylaşılmalı ve sipariş talebiyle karıştırılmamalıdır.", en: "Location information should be shared only as needed and should not be mistaken for a confirmed order." },
    relatedSlugs: ["guvenli-teslim-alma", "yerel-ureticiyi-desteklemek"],
  },
  {
    slug: "guvenli-teslim-alma",
    status: "editorial",
    title: { tr: "Güvenli teslimat ve teslim alma önerileri", en: "Safer delivery and handover practices" },
    summary: { tr: "Teslim biçimi, zaman aralığı, paket kontrolü ve kişisel bilgi sınırları için pratik öneriler.", en: "Practical guidance for delivery method, timing, package checks, and personal-data boundaries." },
    cover: { src: editorialVisuals.delivery, alt: { tr: "Özenle paketlenmiş ürünlerin teslim için hazırlanması", en: "Carefully packed goods prepared for handover" } },
    readingMinutes: 5,
    category: { tr: "Güvenlik", en: "Safety" },
    editorialLabel,
    intro: { tr: "FEMORIA mevcut aşamada ödeme veya teslimat garantisi sunmaz; sayfadaki bilgiler kullanıcıların koşulları daha açık değerlendirmesine yardımcı olur.", en: "At its current stage, FEMORIA does not guarantee payment or delivery; the platform information helps users evaluate terms more clearly." },
    sections: [
      { id: "before", title: { tr: "Teslimden önce", en: "Before handover" }, paragraphs: { tr: ["Ürünün hazırlanma durumu, teslim aralığı ve teslim yöntemini aynı konuşma içinde teyit edin."], en: ["Confirm preparation status, time window, and delivery method in the same conversation."] } },
      { id: "during", title: { tr: "Teslim sırasında", en: "During handover" }, paragraphs: { tr: ["Paketin görünür hasarını kontrol edin. Gıda ürünlerinde üreticinin belirttiği saklama koşullarını teslimden sonra gecikmeden uygulayın."], en: ["Check for visible package damage. For food items, follow the maker's storage guidance promptly after handover."] }, bullets: { tr: ["Kişisel bilgiyi sınırlı paylaşın", "Koşulları yazılı tutun", "Şüpheli talepleri bildirin"], en: ["Limit personal information", "Keep terms in writing", "Report suspicious requests"] } },
    ],
    conclusion: { tr: "Rahatsız olduğunuz veya açık olmayan bir teslim koşulunda süreci durdurun ve açıklama isteyin.", en: "Pause and ask for clarification whenever a handover condition feels uncomfortable or unclear." },
    relatedSlugs: ["yakindaki-ureticilerden-alisveris", "femoria-dogrulama-yaklasimi"],
  },
  {
    slug: "kucuk-uretim-seri-uretim",
    status: "editorial",
    title: { tr: "Küçük üretim ile seri üretim arasındaki farklar", en: "Small-batch and mass production: key differences" },
    summary: { tr: "Ölçek, tutarlılık, hazırlık süresi ve ürün farklılıklarını dengeli biçimde karşılaştırma.", en: "A balanced comparison of scale, consistency, lead time, and variation." },
    cover: { src: editorialVisuals.care, alt: { tr: "Küçük üretim için düzenlenmiş sade çalışma alanı", en: "A calm workspace arranged for small-batch production" } },
    readingMinutes: 5,
    category: { tr: "Üretim süreci", en: "Making process" },
    editorialLabel,
    intro: { tr: "Küçük ve seri üretim farklı ihtiyaçlara cevap verir; biri her durumda diğerinden üstün değildir.", en: "Small-batch and mass production serve different needs; neither is universally better." },
    sections: [
      { id: "scale", title: { tr: "Ölçek ve süre", en: "Scale and timing" }, paragraphs: { tr: ["Küçük üretimde ürünler sınırlı adetle veya talep sonrasında hazırlanabilir. Bu, stok ve teslim süresinin değişken olabileceği anlamına gelir."], en: ["Small-batch items may be produced in limited quantities or after a request, so stock and lead times can vary."] } },
      { id: "variation", title: { tr: "Tutarlılık ve doğal farklılık", en: "Consistency and natural variation" }, paragraphs: { tr: ["El işçiliği, özellikle sır, doku ve desen gibi alanlarda küçük farklılıklar yaratabilir. Ürün açıklaması kabul edilebilir değişimi anlatmalıdır."], en: ["Handwork can create small differences in glaze, texture, or pattern. The product description should explain acceptable variation."] }, bullets: { tr: ["İhtiyacınız olan adedi değerlendirin", "Hazırlık süresini karşılaştırın", "Birebir aynılık beklentinizi belirtin"], en: ["Consider the quantity you need", "Compare lead times", "State if exact matching is important"] } },
    ],
    conclusion: { tr: "Doğru seçim, üretim biçimini kullanım amacınız ve zaman planınızla eşleştirmektir.", en: "The right choice matches the production method to your intended use and timeline." },
    relatedSlugs: ["siparis-uzerine-uretim", "yerel-ureticiyi-desteklemek"],
  },
  {
    slug: "femoria-dogrulama-yaklasimi",
    status: "editorial",
    title: { tr: "FEMORIA’da üretici doğrulama yaklaşımı", en: "FEMORIA's maker verification approach" },
    summary: { tr: "Profil bilgilerinin incelenmesi ile ürün veya işlem garantisi arasındaki farkı açıklar.", en: "Explains the difference between profile review and a product or transaction guarantee." },
    cover: { src: editorialVisuals.guideDesk, alt: { tr: "Notlar ve ürün bilgileriyle yapılan editoryal inceleme", en: "An editorial review with notes and product information" } },
    readingMinutes: 4,
    category: { tr: "Şeffaflık", en: "Transparency" },
    editorialLabel,
    intro: { tr: "Doğrulama rozeti, profilin platformun mevcut inceleme adımlarından geçtiğini gösterir; sertifika, ürün garantisi veya hukuki uygunluk beyanı değildir.", en: "A verification badge indicates that a profile has passed the platform's current review steps; it is not a certification, product guarantee, or legal-compliance statement." },
    sections: [
      { id: "scope", title: { tr: "İncelemenin kapsamı", en: "Scope of review" }, paragraphs: { tr: ["Başvuru sırasında sunulan kimlik, profil ve üretim alanı bilgileri mevcut süreç kapsamında kontrol edilebilir. İnceleme kapsamı platform geliştikçe açıkça güncellenmelidir."], en: ["Identity, profile, and production-area information submitted during an application may be reviewed under the current process. The scope should be updated transparently as the platform develops."] } },
      { id: "responsibility", title: { tr: "Kullanıcının değerlendirmesi devam eder", en: "Users still need to evaluate each listing" }, paragraphs: { tr: ["Ürün açıklamasını, malzemeyi, alerjen bilgisini ve teslim koşulunu ayrıca değerlendirin. Şüpheli veya tutarsız içerikleri bildirin."], en: ["Review the product description, materials, allergen information, and delivery terms separately. Report suspicious or inconsistent content."] }, bullets: { tr: ["Rozeti garanti olarak yorumlamayın", "Ürün bilgilerini ayrıca kontrol edin", "Şüpheli içeriği bildirin"], en: ["Do not interpret the badge as a guarantee", "Check product details separately", "Report suspicious content"] } },
    ],
    conclusion: { tr: "Şeffaf doğrulama, neyin kontrol edildiğini ve neyin edilmediğini açıkça söylemekle başlar.", en: "Transparent verification begins by stating clearly what is and is not reviewed." },
    relatedSlugs: ["guvenli-teslim-alma", "el-yapimi-urun-kontrol-listesi"],
  },
] satisfies GuideArticle[];

export function getGuideBySlug(slug: string): GuideArticle | null {
  return guideArticles.find((guide) => guide.slug === slug) ?? null;
}

export function getRelatedGuides(guide: GuideArticle): GuideArticle[] {
  return guide.relatedSlugs.flatMap((slug) => {
    const related = getGuideBySlug(slug);
    return related ? [related] : [];
  });
}
